Valour-Software/Valour

- FAQ.md
2 new questions added and 'How can I help?' has info about possible future gofundme. 
**_Also @SpikeViper if you can confirm this is actually true_**
> Updating FAQ.md

- FAQ.md
11th and 15th lines needed minor correcting.
> Minor corrections to FAQ.md

- .github/ISSUE_TEMPLATES/---board-feature-request.md
- .github/ISSUE_TEMPLATES/---bug-report.md
- .github/ISSUE_TEMPLATES/---documentation-request.md
- .github/ISSUE_TEMPLATES/---feature-request.md
This will add the following issue templates:
- Bug reports
- Feature requests
- Developer feature requests
- Wiki edits
> Add Issue Templates

- .github/ISSUE_TEMPLATES/---board-feature-request.md
- .github/ISSUE_TEMPLATES/---bug-report.md
- .github/ISSUE_TEMPLATES/---documentation-request.md
- .github/ISSUE_TEMPLATES/---feature-request.md
- .github/ISSUE_TEMPLATES/config.yml
This adds the issue templates in #62
> Add Issue Templates (final version)

- Valour/Client/Pages/Index.razor
- Valour/Client/Planets/ClientPlanetManager.cs
- Valour/Client/Program.cs
- Valour/Client/SignalRManager.cs
- Valour/Client/wwwroot/js/main.js
Should fix SignalR dropoffs which arent already fixed
> Reconnect system

- Valour/Client/Pages/AgeVeri.razor
- Valour/Client/wwwroot/js/main.js
> Set date fix?

- .gitignore
- FAQ.md
- Valour/Client/Pages/AgeVeri.razor
- Valour/Client/wwwroot/index.html
(also added .idea folder to .gitignore)
> Turned year ifs into a switch and made embed proper colour

- FAQ.md
I was going to do this in my previous or but spike jumped the gun a bit
> Added Spike's requested change to FAQ.md

- Valour/Client/Shared/ChannelWindowComponent.razor
- Valour/Client/wwwroot/js/main.js
- Valour/Server/Controllers/UserController.cs
> Fix scroll

- FAQ.md
Also once this is pulled I will commit the HTML for it to about.valour.gg repo
> Fixed reference and improved signed commits paragraph for FAQ.md

- FAQ.md
Adds content tables and reorganises the categories and answers + new answers
> Major update to FAQ.md

- Valour/Client/Shared/MemberComponent.razor
- Valour/Client/wwwroot/css/app.css
#194 but fixed since spike moved stuff
also fixed indentation on something i cant remember
also as per #194, idk if it will work dont quote me
> Staff tags probably maybe?

- Valour/Client/wwwroot/css/app.css
It removes the component that was making the textbox look like part of it was missing.
> Fix issue #142

- Valour/Client/ContextMenus/MemberContextMenu.cs
- Valour/Client/Pages/Index.razor
- Valour/Client/Planets/ClientPlanetManager.cs
- Valour/Client/Planets/ClientPlanetMember.cs
- Valour/Client/Program.cs
- Valour/Client/Shared/ChannelWindowComponent.razor
- Valour/Client/Shared/EditPlanet/EditRoles/EditPlanetRolesComponent.razor
- Valour/Client/Shared/MemberListComponent.razor
- Valour/Client/Shared/MessageComponent.razor
- Valour/Client/Shared/MessageHolderComponent.razor
- Valour/Client/Shared/UserContextMenuComponent.razor
- Valour/Client/Valour.Client.csproj
- Valour/Client/_Imports.razor
- Valour/Client/wwwroot/js/main.js
- Valour/Server/Controllers/PlanetController.cs
- Valour/Server/Planets/PlanetHub.cs
- Valour/Server/Planets/ServerPlanetMember.cs
- Valour/Server/Roles/ServerPlanetRole.cs
> Magical role systems

- Valour/Client/wwwroot/css/app.css
both of them were alignment issues
> solution to #133 last comment

- Valour/Client/Channels/ClientPlanetChatChannel.cs
- Valour/Client/ClientWindowManager.cs
- Valour/Client/Shared/ChannelWindowComponent.razor
- Valour/Client/Shared/MessageComponent.razor
- Valour/Client/Shared/MessageHolderComponent.razor
- Valour/Server/Controllers/ChannelController.cs
Fixed issue where staged messages are added to every request
> Finally fix the bug of death

- Valour/Server/Categories/ServerPlanetCategory.cs
- Valour/Server/Controllers/PermissionsController.cs
> Better role management permission checking

- Valour/Client/Planets/ClientPlanetMember.cs
- Valour/Client/Shared/EditChannelListItem/EditCLIPermissionsComponent.razor
- Valour/Server/Controllers/PlanetController.cs
- Valour/Shared/Roles/PlanetRole.cs
Prevents users from seeing permission operations they don't actually have access to
> Client-side hiding for disallowed permission operations

- Valour/Client/wwwroot/css/app.css
> solved issue #256 and merge conflict for #255

- Valour/Server/Controllers/UserController.cs
> change token format probably maybe i dont know c# so we hope

- Valour/Client/Planets/ClientPlanetMember.cs
- Valour/Client/Shared/LoginComponent.razor
- Valour/Client/Shared/MemberListComponent.razor
- Valour/Client/Shared/RoleComponent.razor
- Valour/Client/Valour.Client.csproj
- Valour/Client/wwwroot/css/app.css
- Valour/Server/Channels/ServerPlanetChatChannel.cs
- Valour/Server/Controllers/CategoryController.cs
- Valour/Server/Controllers/ChannelController.cs
- Valour/Server/Controllers/PlanetController.cs
- Valour/Server/Planets/ServerPlanet.cs
- Valour/Server/Workers/StatWorker.cs
- Valour/Shared/Users/User.cs
The MemberList will now group members by their role, and there is Online group for members without any showable role. This also created a Offline group. This also will not render members in the memberlist who have not been online in the last 7 days, since it would make no sense to render these.
> Made MemberList group users by Role

- Valour/Client/Messages/ClientPlanetMessage.cs
- Valour/Client/Valour.Client.csproj
> Hotfix for mentions

- Valour.API/Valour.API.csproj
- Valour.API/ValourClient.cs
- Valour.sln
- Valour/Client/App.razor
- Valour/Client/ClientUserManager.cs
- Valour/Client/Pages/AgeVeri.razor
- Valour/Client/Pages/CreatePlanet.razor
- Valour/Client/Pages/ForgotPassword.razor
- Valour/Client/Pages/Invite.razor
- Valour/Client/Pages/RecoverPassword.razor
- Valour/Client/Pages/Register.razor
- Valour/Client/Pages/VerifyEmail.razor
- Valour/Client/Program.cs
- Valour/Client/Shared/BanUserComponent.razor
- Valour/Client/Shared/CreateCategoryComponent.razor
- Valour/Client/Shared/CreateChannelComponent.razor
- Valour/Client/Shared/CreatePlanetComponent.razor
- Valour/Client/Shared/EditChannelListItem/EditChannelListItemComponent.razor
- Valour/Client/Shared/EditPlanet/EditPlanetComponent.razor
- Valour/Client/Shared/EditUser/EditUserComponent.razor
- Valour/Client/Shared/LoginComponent.razor
- Valour/Client/Valour.Client.csproj
- Valour/Server/Database/ValourDB.cs
- Valour/Server/Startup.cs
- Valour/Server/Users/Identity/UserManager.cs
- Valour/Server/Valour.Server.csproj
Hopefully I caught all of the migration issues.
> Migrate to .net 6.0 and create Valour.API project

- Valour/Client/wwwroot/fixboi
This file helps to fix integrity issues on the server side
> Add fix boi

- Valour/Client/Shared/ChannelWindowComponent.razor
> Remove egg

- Valour/Client/wwwroot/js/channel.js
Fixes a thing where enter after mention selector will endlessly add more mentions!
> Fix annoying

- Valour/Client/Shared/Messages/MessageComponent.razor
- Valour/Server/API/BaseAPI.cs
- Valour/Server/Program.cs
- Fix message component bug
- Fix API version bug
> Minor fixes

- Valour/Client/Shared/Windows/ChannelWindows/FileUpload/FileUploadComponent.razor
- Valour/Client/Shared/Windows/ChannelWindows/FileUpload/FileUploadComponent.razor.css
- Valour/Server/API/UploadAPI.cs
> VMPS Update changes

- Valour/Web/Controllers/FAQController.cs
- Valour/Web/FAQ.md
- Valour/Web/MarkdownToHtml.cs
- Valour/Web/Program.cs
- Valour/Web/Valour.Web.csproj
- Valour/Web/Views/FAQ/FAQ.cshtml
- Valour/Web/Views/Shared/_Layout.cshtml
- Valour/Web/wwwroot/css/faq.css
- Valour/Web/wwwroot/css/site.css
Note the FAQ hasn't actually been updated but I will probably get to that tomorrow
> Add FAQ webpage and markdown system

- Valour/API/Client/ValourClient.cs
- Valour/API/Items/Users/TokenRequest.cs
- Valour/Client/Shared/Utility/LoginComponent.razor
This should improve the experience of people who are making bots!
> Quality of Life Improvements to Valour.API

- Valour/Database/Items/Planets/Invite.cs
- Valour/Database/Items/Planets/Members/PlanetBan.cs
- Valour/Database/Items/Planets/Planet.cs
> Make Invite.cs fit with new IPlanetItemAPI and PlanetBan

- Valour/Client/Pages/ConfirmationEmail.razor
- Valour/Client/Pages/Register.razor
- Valour/Server/Database/Items/Users/User.cs
> Better registration errors and allow for resending of email

- Valour/Server/Database/Items/Users/User.cs
Developer and User QOL improvements through redirecting `verify/{code}` to the homepage through `Results.LocalRedirect("/", true, false)` and making the base address not static for password reset and registration emailing (which has also been made into a single function). Also removed `System.` from most Exception classes. I have tested that the link is properly generated when registering so it should work for password recovery as well.
> User.cs Improvements

- Valour/Web/MarkdownToHtml.cs
- Valour/Web/Program.cs
- Valour/Web/Views/Shared/_Layout.cshtml
Also some faq markdown to HTML improvements
> Add App to homepage navbar

- Valour/API/Client/ValourClient.cs
- Valour/API/Items/Authorization/OauthApp.cs
- Valour/API/Items/Authorization/PermissionsNode.cs
- Valour/API/Items/Planets/Channels/PlanetCategoryChannel.cs
- Valour/API/Items/Planets/Channels/PlanetChatChannel.cs
- Valour/API/Items/Planets/Members/PlanetMember.cs
- Valour/API/Items/Planets/Members/PlanetRole.cs
- Valour/API/Items/Planets/Planet.cs
- Valour/API/Items/Planets/PlanetInvite.cs
- Valour/API/Items/Users/User.cs
- Valour/Client.Blazor/App.razor
- Valour/Client/Components/Planets/CreatePlanetComponent.razor
- Valour/Client/Components/Utility/LoginComponent.razor
- Valour/Server/Program.cs
Fix login error messages, make all routes return TaskResult for error handling
> Error Handling (For Coca)

- Valour/Client/wwwroot/css/app.css
This fixes the first error shown in #624 but not the 2nd
1st error fixed:
> Fix user's status being too big

- Valour/Client/Components/ChannelList/ChannelListComponent.razor
- Valour/Client/Components/MemberList/MemberComponent.razor
- Valour/Client/Components/MemberList/MemberComponent.razor.css
- Valour/Client/Components/MemberList/MemberListComponent.razor
- Valour/Client/Components/MemberList/MemberListComponent.razor.css
- Valour/Client/Components/MemberList/RoleComponent.razor
- Valour/Client/Components/MemberList/RoleComponent.razor.css
- Valour/Client/_Imports.razor
- Valour/Client/wwwroot/css/app.css
- Valour/Shared/Items/Users/UserState.cs
- Allow right click on member list name for member management
- Fix scrolling issues
- Make long statuses clip with ellipses; except when mouse hover
- Role name text slides for a "Preview" effect
> Major Member List Improvements

- Valour/API/Nodes/Node.cs
- Valour/Client/Components/Windows/ChannelWindows/ChannelWindowComponent.razor
- Valour/Client/Components/Windows/ChannelWindows/MessageHolderComponent.razor
- Valour/Client/wwwroot/index.html
- Valour/Client/wwwroot/js/main.js
- Valour/Server/Workers/PlanetMessageWorker.cs
Fixes:
- https://github.com/Vooper-Media-LLC/Valour/issues/668
- Duplicate message issues
- Scrolling issues
> Major bug fixes

- Valour/Client/Categories/ClientCategoryManager.cs
- Valour/Client/Components/ChannelList/ChannelListCategoryComponent.razor
- Valour/Client/Components/ChannelList/ChannelListCategoryComponent.razor.css
- Valour/Client/Components/ChannelList/ChannelListPlanetComponent.razor
- Valour/Client/Components/ChannelList/ChannelListPlanetComponent.razor.css
- Valour/Client/Components/FriendsList/FriendComponent.razor.css
Make the channel list follow color scheme and make friends list names less blinding
> Colors (oops reverse merge)

- Valour/API/Valour.Api.csproj
- Valour/Server/Api/Dynamic/DirectChatChannelApi.cs
- Valour/Server/Hubs/ConnectionTracker.cs
- Valour/Server/Services/CoreHubService.cs
- Valour/Server/Services/DirectChatChannelService.cs
- Valour/Server/Services/EcoService.cs
- Valour/Server/Services/NodeService.cs
- Valour/Server/Workers/Economy/TransactionWorker.cs
- Valour/Shared/Valour.Shared.csproj
- Valour/Web/Views/Home/Index.cshtml
If this goes properly, live direct messaging should work between different logical nodes
> [V0.1.9.1] Inter-Node Communications

- Valour/Client/Components/Sidebar/MemberList/MemberListComponent.razor
Adds a new IComparer to sort alphabetically by name in the member list sidebar.
> Alphabetizes the member list for planets

- Valour/Server/Services/RegisterService.cs
- Valour/Server/Services/UserService.cs
Adds new HTML for the forgot password email.
> Improves formatting for password reset email

- Valour/Client/Components/Users/ProfileCard.razor
- Valour/Client/Components/Users/ProfileCard.razor.css
Adds text to the profile badge for offline users displaying when they were last online.
> Profile badge last online

- Valour/Shared/Models/UserUtils.cs
Create the EmailDomainToDotCom method for non .com email domains
> Create proton.me workaround

- .gitignore
- Valour/Server/Properties/launchSettings.json
Also remove Properties/ from .gitignore to allow for launchSettings.json to be published
> Fix quicklaunch by adding launchSettings

- Valour/Client/Components/Menus/Modals/ConfirmModalComponent.razor
- Valour/Client/Components/Menus/Modals/Users/Edit/EditUserComponent.razor
> Confirmation message when logging out

- Valour/Client/Components/Menus/Modals/Planets/Edit/EditRoles/EditPlanetRolesComponent.razor.css
Bug image on Trello, fixed image below.
> Remove width restriction on button

- Valour/Client/Components/Menus/Modals/Users/Edit/EditUserInfoComponent.razor
- Valour/Client/Components/Utility/ImageCropper.razor
- Valour/Client/Components/Utility/ImageCropper.razor.css
- Valour/Client/Components/Utility/ImageCropper.razor.js
- Valour/Client/wwwroot/index.html
- add reusable `ImageCropper` component with JS wrapper and styles
- enable `ImageCropper` when uploading avatars in `EditUserInfoComponent`
- load Cropper.js library in the site
- `dotnet build Valour.sln -c Release` *(fails: `dotnet` not found)*
> Add avatar image cropper

- Valour/Server/Api/Dynamic/PlanetRoleApi.cs
- fix mismatched route parameter names for updating and deleting roles
- `git status --short`
> Fix role update/delete route parameter

- Valour/Client/Components/Messages/Attachments/InviteAttachmentComponent.razor
- Valour/Client/Components/Messages/Attachments/InviteAttachmentComponent.razor.css
- Valour/Client/Components/Windows/ChannelWindows/InputComponent.razor
- Valour/Client/Messages/MessageAttachmentExtensions.cs
- show inline planet invites in chat
- display join button with planet info
- `dotnet --version` *(fails: command not found)*
> Add chat invite attachment

- Valour/Client/Components/Menus/Modals/Planets/Edit/EditPlanetBansComponent.razor
- Valour/Client/Components/Menus/Modals/Planets/Edit/EditPlanetComponent.razor
- Valour/Client/Components/Menus/Modals/Planets/Edit/EditPlanetUsersComponent.razor
- add ability to pass planet info into members and bans menus
- build EditPlanetUsersComponent with member table and kick/ban actions
- build EditPlanetBansComponent with ban table and edit/delete actions
- `./dotnet/dotnet test Valour.sln -c Release -v minimal` *(fails: NU1301 - failed to retrieve packages)*
> Implement member and ban menus

- Valour/Client/Components/Menus/Modals/Planets/Edit/Moderation/AutomodActionModal.razor
- Valour/Client/Components/Menus/Modals/Planets/Edit/Moderation/AutomodTriggerModal.razor
- Valour/Client/Components/Utility/RoleDropdown.razor
- Valour/Client/Components/Utility/RoleDropdown.razor.css
- add RoleDropdown component to select roles with pill tags
- use RoleDropdown in automod action modal
- turn automod trigger modal into a simple two-step wizard
- `npm test` *(fails: Error: no test specified)*
- `dotnet test --no-build` *(fails: dotnet not found)*
> Implement automod wizard and role dropdown

- Valour/Client/Components/Utility/CustomDropdown.razor
- Valour/Client/Components/Utility/CustomDropdown.razor.css
- Valour/Client/Components/Utility/CustomDropdownContent.razor
- Valour/Client/Components/Utility/CustomDropdownContent.razor.css
- Valour/Client/Components/Utility/CustomDropdownContentData.cs
- Valour/Client/Pages/Index.razor
- add CustomDropdown and CustomDropdownContent components for advanced dropdowns
- allow custom item rendering and searching
- support mobile-friendly dropdown overlay
- wire dropdown overlay into the main page
- `dotnet test --no-build` *(fails: command not found)*
> Add CustomDropdown component

- Valour/Client/Components/Utility/CustomDropdown.razor
- Valour/Client/Components/Utility/CustomDropdown.razor.css
- Valour/Client/Components/Utility/CustomDropdownContent.razor
- Valour/Client/Components/Utility/CustomDropdownContent.razor.css
- Valour/Client/Components/Utility/CustomDropdownContentData.cs
- style CustomDropdown to look like inputs
- indicate the selected choice with border & checkmark
- surface the selected item in dropdown data
- `./dotnet/dotnet test` *(fails: Failed to retrieve information about packages)*
> Improve dropdown usability
